-- MySQL Script generated by MySQL Workbench
-- Thursday March 19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ComponentType`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `mydb`.`ComponentType` ;

-- CREATE TABLE IF NOT EXISTS `mydb`.`ComponentType` (
--   `type_id` INT NOT NULL,
--   `type` VARCHAR(45) NULL,
--   PRIMARY KEY (`type_id`))
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Driver` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Driver` (
  `username` VARCHAR(25) NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(25) NULL,
  `lName` VARCHAR(25) NULL,
  `email` VARCHAR(30) NULL,
  `password` VARCHAR(15) NOT NULL,
  `street` VARCHAR(30) NULL,
  `city` VARCHAR(20) NULL,
  `state` VARCHAR(15) NULL,
  `zip` int NULL,
  `carModel` VARCHAR(25) NULL,
  `liscensePlate` VARCHAR(10) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Homeowner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Homeowner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Homeowner` (
  `username` VARCHAR(25) NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(25) NULL,
  `lName` VARCHAR(25) NULL,
  `email` VARCHAR(30) NULL,
  `password` VARCHAR(15) NOT NULL,
  `street` VARCHAR(30) NULL,
  `city` VARCHAR(20) NULL,
  `state` VARCHAR(15) NULL,
  `zip` int NULL,
  `numOfSpots` int NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
