-- MySQL Script generated by MySQL Workbench
-- Thursday March 19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spots` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `spots` ;

-- -----------------------------------------------------
-- Table `mydb`.`ComponentType`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `mydb`.`ComponentType` ;

-- CREATE TABLE IF NOT EXISTS `mydb`.`ComponentType` (
--   `type_id` INT NOT NULL,
--   `type` VARCHAR(45) NULL,
--   PRIMARY KEY (`type_id`))
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spots`.`Driver` ;

CREATE TABLE IF NOT EXISTS `spots`.`Driver` (
  userId INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(25) NOT NULL, 
  fName VARCHAR(25) NULL,
  lName VARCHAR(25) NULL,
  email VARCHAR(30) NULL,
  password VARCHAR(15) NOT NULL,
  street VARCHAR(30) NULL,
  city VARCHAR(20) NULL,
  state VARCHAR(15) NULL,
  zip int(5) NULL,
  carModel VARCHAR(25) NULL,
  licensePlate VARCHAR(10) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Homeowner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spots`.`Homeowner` ;

CREATE TABLE IF NOT EXISTS `spots`.`Homeowner` (
  userId INT(11) NOT NULL AUTO_INCREMENT, 
  `username` VARCHAR(25) NOT NULL,
  `fName` VARCHAR(25) NULL,
  `lName` VARCHAR(25) NULL,
  `email` VARCHAR(30) NULL,
  `password` VARCHAR(15) NOT NULL,
  `street` VARCHAR(30) NULL,
  `city` VARCHAR(20) NULL,
  `state` VARCHAR(15) NULL,
  `zip` int(5) NULL,
  `numOfSpots` int NULL,
  PRIMARY KEY (userId))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `spots`.`Events` (
	eventId INT(11) NOT NULL AUTO_INCREMENT,
    `eventname` VARCHAR(50) NOT NULL, 
    `date` INT(8) NOT NULL, 
    `startTime` INT(4) NULL, 
    `endTime` INT(4) NULL, 
    `category` VARCHAR(25) NOT NULL, 
    `address` VARCHAR(50) NOT NULL,
    `city` VARCHAR(20) NOT NULL, 
    `state` VARCHAR(2) NOT NULL, 
    `zipcode` INT(5) NOT NULL, 
    PRIMARY KEY (eventId))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
